- README.md
We've introduced mvnw, we don't need Maven anyway.
> Trivial - updating README.txt

- .github/signatures/v1/cla.json
- .github/workflows/cla.yml
Move CLA `signatures` folder to `.github`.
Hide details about signatures from the root folder.
> Move signatures folder to .github

- .github/workflows/cla.yml
- signatures/v1/cla.json
Fixing an invalid individual CLA agreement url in GH Action.
> Fixing invalid CLA url for agreed PRs.

- distribution/src/main/docker/nginx/default.conf
A custom health endpoint.
Health endpoint is independent of any particular cloud provider and can be used by the cluster orchestrator to validate container health status.
> Add health endpoint to nginx

- pom.xml
- tests/end-to-end/tests/lunatitle.cy.ts
Update CMS and Howlite versions
Update CMS and Howlite versions to the latest versions
The new version of CMS (1.2.0) and Howlite (1.0.1) was released. Those versions are updated due to the possibility of using the latest features.
> Update CMS version

- pom.xml
> Update Bulma version

- environment/README.md
- environment/local/admin_password.txt
- environment/local/docker-compose.yml
> Update the documentation related to changing wsadmin password

- tests/end-to-end/package-lock.json
- tests/end-to-end/package.json
- tests/end-to-end/pom.xml
- tests/end-to-end/support/commands.ts
- tests/end-to-end/support/index.ts
- tests/end-to-end/tests/lunatitle.cy.ts
> Fix e2e tests. Wait to ensure if instance is up.

- .github/workflows/ci-dev.yml
> Changed name of the workflow

- pom.xml
> Update Bulma and WebSight CMS versions

- README.md
> Note explaining using nip.io

- application/backend/pom.xml
- application/pom.xml
- content/pom.xml
- distribution/pom.xml
- pom.xml
- tests/content/pom.xml
- tests/end-to-end/pom.xml
- tests/pom.xml
> Revert version update

- application/backend/pom.xml
- application/pom.xml
- content/pom.xml
- distribution/pom.xml
- pom.xml
- tests/content/pom.xml
- tests/end-to-end/pom.xml
- tests/pom.xml
> Fix/revert 1.5.1

- application/backend/pom.xml
- application/pom.xml
- content/pom.xml
- distribution/pom.xml
- pom.xml
- tests/content/pom.xml
- tests/end-to-end/pom.xml
- tests/pom.xml
> Prepare to release version 1.6.0

- application/backend/src/main/resources/apps/luna/components/quote/dialog/.content.json
Howlite components have been updated to look properly in the upcoming side panel feature.
> WS-2172: Prepare components for side panel

- distribution/src/main/docker/nginx/Dockerfile
- distribution/src/main/docker/nginx/nginx.conf
> default config

- application/backend/pom.xml
- application/frontend/pom.xml
- application/pom.xml
- content/pom.xml
- distribution/pom.xml
- distribution/src/main/features/bulma.json
- pom.xml
- tests/content/pom.xml
- tests/end-to-end/pom.xml
- tests/end-to-end/tests/accordion.cy.ts
- tests/end-to-end/tests/carousel.cy.ts
- tests/end-to-end/tests/lunatitle.cy.ts
- tests/end-to-end/tests/quote.cy.ts
- tests/pom.xml
> Prepare to release version 1.7.0

- application/backend/pom.xml
- application/backend/src/main/java/pl/ds/luna/lowcode/components/models/QuoteComponent.java
- application/backend/src/test/java/pl/ds/luna/lowcode/components/models/QuoteComponentTest.java
- application/pom.xml
- tests/end-to-end/tests/quote.cy.ts
> Handle urls

- pom.xml
> [GH-79] Resolve problems with build distribution module on Windows

- application/backend/pom.xml
- application/frontend/pom.xml
- application/pom.xml
- content/pom.xml
- distribution/pom.xml
- pom.xml
- tests/content/pom.xml
- tests/end-to-end/pom.xml
- tests/end-to-end/tests/accordion.cy.ts
- tests/end-to-end/tests/carousel.cy.ts
- tests/end-to-end/tests/lunatitle.cy.ts
- tests/end-to-end/tests/quote.cy.ts
- tests/pom.xml
> Release 1.8.0

- tests/end-to-end/package-lock.json
- tests/end-to-end/package.json
- tests/end-to-end/support/commands.ts
- tests/end-to-end/support/types.ts
> Using cypress queries

- application/backend/pom.xml
- application/frontend/pom.xml
- application/pom.xml
- content/pom.xml
- distribution/pom.xml
- pom.xml
- tests/content/pom.xml
- tests/end-to-end/pom.xml
- tests/pom.xml
> cms version update

- application/backend/pom.xml
- application/frontend/pom.xml
- application/pom.xml
- content/pom.xml
- distribution/pom.xml
- pom.xml
- tests/content/pom.xml
- tests/end-to-end/pom.xml
- tests/end-to-end/tests/accordion.cy.ts
- tests/end-to-end/tests/carousel.cy.ts
- tests/end-to-end/tests/lunatitle.cy.ts
- tests/end-to-end/tests/quote.cy.ts
- tests/pom.xml
> Update tests due to changes in CMS SNAPSHOT

- application/backend/pom.xml
- application/frontend/pom.xml
- application/pom.xml
- content/pom.xml
- distribution/pom.xml
- pom.xml
- tests/content/pom.xml
- tests/end-to-end/pom.xml
- tests/pom.xml
Update CMS, Howlite, and Bulma versions
> Update CMS, Howlite, and Bulma version

- README.md
> Trivial: README typo fix

- application/backend/pom.xml
- application/frontend/pom.xml
- application/pom.xml
- content/pom.xml
- distribution/pom.xml
- pom.xml
- tests/content/pom.xml
- tests/end-to-end/pom.xml
- tests/pom.xml
> cms 1.12.0 release

- application/backend/pom.xml
- application/frontend/pom.xml
- application/pom.xml
- content/pom.xml
- distribution/pom.xml
- pom.xml
- tests/content/pom.xml
- tests/end-to-end/pom.xml
- tests/pom.xml
> Release 1.14.0

- .github/workflows/cla.yml
- CONTRIBUTING.md
- README.md
> Update script url

- application/backend/pom.xml
- application/frontend/pom.xml
- application/pom.xml
- content/pom.xml
- distribution/pom.xml
- pom.xml
- tests/content/pom.xml
- tests/end-to-end/pom.xml
- tests/pom.xml
> Update CMS to 1.16.0

- application/backend/pom.xml
- application/frontend/pom.xml
- application/pom.xml
- content/pom.xml
- distribution/pom.xml
- pom.xml
- tests/content/pom.xml
- tests/end-to-end/pom.xml
- tests/pom.xml
> Release 1.18.0

- README.md
- distribution/pom.xml
- distribution/src/main/docker/nginx/Dockerfile
- distribution/src/main/docker/nginx/html/Personal.html
- distribution/src/main/docker/nginx/kyanite.conf
- distribution/src/main/docker/nginx/lowcodeluna.conf
- distribution/src/main/docker/nginx/nocodeluna.conf
> fix demo sites configs

- distribution/pom.xml
> minor pom update

- application/backend/pom.xml
- application/frontend/pom.xml
- application/pom.xml
- content/pom.xml
- distribution/pom.xml
- pom.xml
- tests/content/pom.xml
- tests/end-to-end/pom.xml
- tests/pom.xml
> CMS version bump: 1.20.0

- distribution/pom.xml
- tests/end-to-end/pom.xml
Remove dangling volumes after building the project.
> Enable removing volumes

- .github/workflows/ci-dev.yml
Update ci-dev.yml to use correct command for e2e functional tests.
In this PR https://github.com/websight-io/starter/pull/173 I forgot to update `ci-dev.yml` workflow
> WOS-336 update ci-dev.yml to use correct command for e2e functional tests

- distribution/README.md
https://teamds.atlassian.net/browse/WS-2473
> Update java -jar command

- application/backend/pom.xml
- application/frontend/pom.xml
- application/pom.xml
- content/pom.xml
- distribution/pom.xml
- pom.xml
- tests/content/pom.xml
- tests/end-to-end/pom.xml
- tests/pom.xml
> WS-2920 Release: Update CMS version

- application/backend/src/main/resources/apps/luna/components/accordion/.content.json
- application/backend/src/main/resources/apps/luna/components/carousel/.content.json
- application/backend/src/main/resources/apps/luna/components/carousel/carousel.html
- application/backend/src/main/resources/apps/luna/components/carousel/carouselitem/.content.json
- application/backend/src/main/resources/apps/luna/components/carousel/carouselitem/carouselitem.html
- application/backend/src/main/resources/apps/luna/components/quote/.content.json
- application/backend/src/main/resources/apps/luna/policies/.content.json
- application/backend/src/main/resources/apps/luna/templates/articlepage/policies/.content.json
- application/backend/src/main/resources/apps/luna/templates/homepage/policies/.content.json
- application/frontend/src/components/Carousel/carousel.scss
- application/frontend/src/components/Carousel/carousel.ts
- content/src/main/content/jcr_root/content/lowcodeluna/pages/About/.content.xml
- content/src/main/content/jcr_root/content/lowcodeluna/pages/Catalog/.content.xml
- content/src/main/content/jcr_root/content/lowcodeluna/pages/Homepage/.content.xml
- content/src/main/content/jcr_root/content/lowcodeluna/pages/Products/.content.xml
- content/src/main/content/jcr_root/content/nocodeluna/pages/About/.content.xml
- content/src/main/content/jcr_root/content/nocodeluna/pages/Catalog/.content.xml
- content/src/main/content/jcr_root/content/nocodeluna/pages/Homepage/.content.xml
- content/src/main/content/jcr_root/content/nocodeluna/pages/Products/.content.xml
- pom.xml
- tests/end-to-end/tests/carousel.cy.ts
This reverts commit cd19e82d51c072b4950350979875b685dd9ccd41.
> Revert "Revert "WS-2920 Release: Update Kyanite""

- content/src/main/content/jcr_root/content/lowcodeluna/pages/About/.content.xml
- content/src/main/content/jcr_root/content/lowcodeluna/pages/Catalog/.content.xml
- content/src/main/content/jcr_root/content/lowcodeluna/pages/Homepage/.content.xml
- content/src/main/content/jcr_root/content/lowcodeluna/pages/Products/.content.xml
- content/src/main/content/jcr_root/content/luna/pages/Homepage/.content.xml
- content/src/main/content/jcr_root/content/nocodeluna/pages/Homepage/.content.xml
Remove blog from navigation.
Blog is the very first item in the navigation but it is a dummy item and doesn’t work.
> WOS-160 remove blog from navigation

- pom.xml
> WS-2939 Release hotfix

- pom.xml
> WS-2939 Update Howlite

- pom.xml
> WS-2959 Release Hotfix

- .github/workflows/ephemeral-env-create.yml
- .github/workflows/ephemeral-env-destroy.yml
- .github/workflows/release.yml
- distribution/pom.xml
- environment/README.md
- environment/remote-gcp-cloudrun/README.md
- environment/remote-gcp-cloudrun/service.tmpl.yaml
Enable development team to work with ephemeral environments they are meant to be used for development purposes only (e.g. for bugfix/feature testing or demo).
Developers should be able able to spin temporal cloud environment from a custom branch for testing/demo purposes.
> GCP Cloud Run environment automation

- Dockerfile
Building project with multi-stage Docker build should not check licenses.
Rat failed builds when project was customized.
> Exclude RAT from Dockerfile build

- .github/scripts/ci-verify-build-provide-visual-regression-report.sh
- .github/scripts/ci-verify-build-read-report-failures.sh
- .github/workflows/ci-verify-build.yml
- .gitignore
- content/src/main/content/jcr_root/content/luna/pages/About-Us/.content.xml
Fix visual regression scripts
Scripts paths were not valid.
> Fix visual regression scripts

- Dockerfile
- application/backend/pom.xml
- application/frontend/pom.xml
- application/pom.xml
- content/pom.xml
- distribution/pom.xml
- pom.xml
- tests/content/pom.xml
- tests/end-to-end/pom.xml
- tests/pom.xml
> WS-3069 Update CMS version

- applications/puresight/backend/src/main/resources/apps/puresight/components/templates/carousel.html
- applications/puresight/backend/src/main/resources/apps/puresight/components/templates/tiles.html
Links to products do not work because the links are relative.
Carousel and product listing should work from all pages
> Bugfix: using absolute PureSight product links

- .github/workflows/ci-test-starter-vs-cms-development.yml
- .github/workflows/ci-verify-build.yml
- .github/workflows/ci-verify-dev-journey.yml
- .github/workflows/release-build-and-publish-images.yml
- .mvn/extensions.xml
- Dockerfile
- applications/luna-low-code/backend/src/test/java/pl/ds/luna/lowcode/components/models/QuoteComponentTest.java
- pom.xml
Migrate Starter CI to use GCP Artifacts Registry
> WS-3230 Migrate Starter to GCP

- applications/puresight/frontend/src/components/ImageCarousel/ImageCarousel.scss
> WSIO-755 Fix swapping column issue

- applications/puresight/frontend/src/components/BlogTemplates/BlogTemplates.scss
- applications/puresight/frontend/src/components/BlogTemplates/_index.scss
- applications/puresight/frontend/src/components/index.scss
- applications/puresight/frontend/src/global.scss
- applications/puresight/frontend/src/main.scss
> Wsio 1212 set logo dimension

- applications/puresight/content/src/main/content/jcr_root/content/puresight/pages/homepage/.content.xml
- applications/puresight/content/src/main/content/jcr_root/content/puresight/pages/templates/product/.content.xml
- applications/puresight/content/src/main/content/jcr_root/etc/groovy-console/puresight/publish-components.groovy
- applications/puresight/frontend/src/components/Search/search.ts
- applications/puresight/frontend/src/components/Search/test-data.ts
> [DXP-1146] puresight  update to short paths

- applications/puresight/frontend/src/components/Search/service.ts
- pom.xml
> [DXP-1146] update streamx version to 0.0.42 and adjust to new search format

- pom.xml
> [DXP-1404] Update demo to latest versions

- applications/puresight/frontend/src/components/Search/service.ts
Blueprint's endpoint exposing search was changed.
> [DXP-1363] Adjust to new search endpoint
